### ISSUE TITLE
Header plaatsten

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/look-and-feel-corporate-identity#12]

**Comment by SamaraFellaDina** [comment]
@Naddybs Je kan hier eventueel issues plaatsen :)

**Comment by Naddybs** [comment]
https://github.com/SamaraFellaDina/look-and-feel-corporate-identity/blob/3a12ead36574e5bf7c8f90106e3896c38e83fab4/styles/styles.css#L75-L79

- Hi, om elementen te positioneren kan je in dit geval position absolute gebruiken. (niet te vaak doen) Het element wordt absoluut gepositioneerd ten opzichte van zijn eerst relatieve gepositioneerde parent element. 
- In dit geval wil je "navlist-right' items rechts positioneren, dan gebruik je 'right: (..)em;'
- regel 77 kan je weghalen

**Comment by Naddybs** [comment]
**Dit gaat over CSS**
Het onderstaande kan je weglaten:
- regel 54 t/m 56
- regel 59
- regel 84 en 85
- regel 106

Hebben geen functie, overbodig

**Comment by Naddybs** [comment]
**Dit gaat over HTML**
https://github.com/SamaraFellaDina/look-and-feel-corporate-identity/blob/3a12ead36574e5bf7c8f90106e3896c38e83fab4/index.html#L8
- Vervang de backslash door een schuine streep. Zorg ervoor dat je dit doet voor alle verwijzingen naar bestanden, mappen of URLs in je HTML-code.

**Comment by Naddybs** [comment]
https://github.com/SamaraFellaDina/look-and-feel-corporate-identity/blob/3a12ead36574e5bf7c8f90106e3896c38e83fab4/index.html#L24-L28

ja ;) alt attribuut nodig

**Comment by Naddybs** [comment]
https://github.com/SamaraFellaDina/look-and-feel-corporate-identity/blob/3a12ead36574e5bf7c8f90106e3896c38e83fab4/index.html#L25-L26C68

- afsluitende i tag gebruikt? images hebben geen afsluitende tag nodig
